### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by manderso7** [firebus/splunk-jira#25]
I'm not being deliberately obtuse :), but I am not getting any data from the search job. I've installed the app on my search head, opened my FW to the Jira server from my search head, but I don't see any data coming into the search. Where do I need to install this app?

Thanks

Suppose I should elaborate:
on my search head I've got $SPLUNK_HOME/etc/apps/jira/local/jira.conf & $SPLUNK_HOME/etc/apps/jira/bin/config.ini, w/ my local Jira config (host, username, port, so on).
I can telnet lira.domain.com 80 from the search head where I've installed the app. However, I'm getting Connection failed under status monitoring for the Jira server.

**Comment by firebus** [comment]
Hi there! I'm sorry for taking so long to reply.

The app should be in /etc/apps/jira so that looks right.

What's your search query?

There needs to be better logging for the rest command, but since there's not, you can edit bin/jira_rest.py to add some.

At the top of the file add:
import splunk.mining.dcutils as dcu

At line 367 in the # issues block, right before the variable "fieldtarget" is set, add:
dcu.getLogger().info(req.get_full_url())

It's python so make sure to match the indentation of the previous line.

Having added this logging, you should see the URL that the app is calling in $SPLUNK_HOME/var/log/splunk/python.log on the search head.

Call the same URL using cURL or similar from your search head. Whether or not you get results back outside the app will help diagnose where the problem is.

**Comment by zjiaran** [comment]
Would be happy to assist if this is still an issue.

**Comment by manderso7** [comment]
Thanks much, but we got it installed. Sorry I didn't get back to you sooner.
